---

version: '3'
services:
  influx:
    image: "influxdb:1.5"
    # ports:
    #  - "8086:8086"
    volumes:
     - /srv/influxdb:/var/lib/influxdb:z
    environment:
    - INFLUXDB_DB=db0 
    - INFLUXDB_ADMIN_ENABLED=true
    - INFLUXDB_ADMIN_USER=admin 
    - INFLUXDB_ADMIN_PASSWORD=supersecretpassword
    - INFLUXDB_USER=telegraf 
    - INFLUXDB_USER_PASSWORD=secretpassword
    networks:
      - monnet
  grafana:
    image: grafana/grafana:6.1.4
    ports:
     - 3000:3000
    environment:
    - "GF_SECURITY_ADMIN_PASSWORD=secret"
    volumes:
    - /srv/grafana:/var/lib/grafana:z
    networks:
      - monnet
  telegraf:
    image: telegraf:1.10-alpine
    environment:
      - HOST_PROC=/host/proc
    volumes:
      - /srv/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /proc:/host/proc:z
      - /var/run/docker.sock:/var/run/docker.sock:z
    networks:
      - monnet



networks:
  monnet: